package GUI;

import Logica.Nodo;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author mdean
 */
public class Editar extends javax.swing.JFrame {
    private Simplificado simplificado;
    private Nodo nodo;
    String directionTmp;//captar direction temporal de la imagen
    /**
     * Creates new form Editar
     */
    public Editar(Nodo nodo, Simplificado simplificado) {
        initComponents();
        setLocationRelativeTo(null); //Centrar la ventana
        this.simplificado = simplificado;
        this.nodo = nodo;
        
        textoNombreEditar(nodo.getNombre());
        formatedFechaEditar(nodo.getFecha());
        textoEmoticonEditar(nodo.getEmoticon());
        textoDescripcionEditar(nodo.getDescripcion());
        mostrarImagen(etiquetaPreviewImageEditar);
        guardarEdicion.setIcon(setIcono("/iconos/save-file.png", guardarEdicion));
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public JLabel mostrarImagen(JLabel fotoLabel) {/*necesitamos crear un Jlabel donde irán las imágenes,
                                                    debemos pasar ese Jlabel como parámetro para que cambie la imagen*/
        try {
            ImageIcon foto;
            foto = new ImageIcon(nodo.getFoto());
            Icon icono;
            icono = new ImageIcon(foto.getImage().getScaledInstance(fotoLabel.getWidth(), fotoLabel.getHeight(), Image.SCALE_DEFAULT));
            fotoLabel.setIcon(icono);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al abrir el archivo");
        }
        return fotoLabel;
    }
    
    public Icon setIcono(String url, JButton bt) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = bt.getWidth();
        int alto = bt.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));

        return icono;
    }
    public void textoNombreEditar(String nombre) {
        this.textoNombreEditar.setText(nombre);
    }
    
    public void formatedFechaEditar(String fecha) {
        this.formatedFechaEditar.setText(fecha);
    }
    
    public void textoEmoticonEditar(String emoticon) {
        this.textoEmoticonEditar.setText(emoticon);
    }
    
    public void textoDescripcionEditar(String Descripcion) {
        this.textoDescripcionEditar.setText(Descripcion);
    }
    
    public void setImagenPreview(Icon imagen) {
        this.etiquetaPreviewImageEditar.setIcon(imagen);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        etiquetaNombre2 = new javax.swing.JLabel();
        etiquetaFecha2 = new javax.swing.JLabel();
        etiquetaEmoticon2 = new javax.swing.JLabel();
        etiquetaDescripcion2 = new javax.swing.JLabel();
        etiquetaPreviewImageEditar = new javax.swing.JLabel();
        textoNombreEditar = new javax.swing.JTextField();
        textoEmoticonEditar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textoDescripcionEditar = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        guardarEdicion = new javax.swing.JButton();
        formatedFechaEditar = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaNombre2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        etiquetaNombre2.setText("Nombre:");
        jPanel2.add(etiquetaNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        etiquetaFecha2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        etiquetaFecha2.setText("Fecha (d/m/yy):");
        jPanel2.add(etiquetaFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        etiquetaEmoticon2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        etiquetaEmoticon2.setText("Emoticón:");
        jPanel2.add(etiquetaEmoticon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        etiquetaDescripcion2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        etiquetaDescripcion2.setText("Descripción:");
        jPanel2.add(etiquetaDescripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        etiquetaPreviewImageEditar.setBackground(new java.awt.Color(0, 0, 0));
        etiquetaPreviewImageEditar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        etiquetaPreviewImageEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaPreviewImageEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(etiquetaPreviewImageEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 410, 410));

        textoNombreEditar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        textoNombreEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreEditarActionPerformed(evt);
            }
        });
        jPanel2.add(textoNombreEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 210, -1));

        textoEmoticonEditar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        textoEmoticonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEmoticonEditarActionPerformed(evt);
            }
        });
        jPanel2.add(textoEmoticonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 45, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setText("Galería vacía");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        textoDescripcionEditar.setColumns(1);
        textoDescripcionEditar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        textoDescripcionEditar.setRows(5);
        jScrollPane4.setViewportView(textoDescripcionEditar);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 310, 190));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Editar Imagen");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, 40));

        guardarEdicion.setBackground(new java.awt.Color(255, 255, 255));
        guardarEdicion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        guardarEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarEdicionActionPerformed(evt);
            }
        });

        jPanel2.add(guardarEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 660, 80, 80));
        formatedFechaEditar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanel2.add(formatedFechaEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 140, -1));
        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 170));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoNombreEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreEditarActionPerformed

    }//GEN-LAST:event_textoNombreEditarActionPerformed

    private void textoEmoticonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEmoticonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEmoticonEditarActionPerformed

    private void guardarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarEdicionActionPerformed
        setVisible(false); // Con esto la ventana "Editar" deja de ser visible
        
        nodo.setNombre(textoNombreEditar.getText());
        nodo.setFecha(formatedFechaEditar.getText());
        nodo.setEmoticon(textoEmoticonEditar.getText());
        nodo.setDescripcion(textoDescripcionEditar.getText());
        simplificado.mostrarDatos();
        

    }//GEN-LAST:event_guardarEdicionActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaDescripcion2;
    private javax.swing.JLabel etiquetaEmoticon2;
    private javax.swing.JLabel etiquetaFecha2;
    private javax.swing.JLabel etiquetaNombre2;
    private javax.swing.JLabel etiquetaPreviewImageEditar;
    private javax.swing.JFormattedTextField formatedFechaEditar;
    private javax.swing.JButton guardarEdicion;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea textoDescripcionEditar;
    private javax.swing.JTextField textoEmoticonEditar;
    private javax.swing.JTextField textoNombreEditar;
    // End of variables declaration//GEN-END:variables
}
