/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logica.Metodos;
import Logica.Nodo;
import javax.swing.JOptionPane;


public class Simplificado extends javax.swing.JFrame {
    Metodos metodo = new Metodos();
    Nodo primer = null, ultimo = null, aux;//punteros
    /**
     * Creates new form simplificado
     */
    public Simplificado() {
        initComponents();
    }

    void  borrarDatos(){
        jTextFieldName.setText("");
        jTextFieldDate.setText("");
        jTextFieldID.setText("");
        jLabelImage1.setIcon(null);
        jLabelImage1.setText("");
        
    }
    
    void irPrincipio(){
        aux = primer;
    }
    
    void irFinal() {
        aux = ultimo;
    }
    
    public void setImagenJLabel(String direccionImagen) {
        metodo.mostrarImagen(jLabelImage, direccionImagen);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedInteract = new javax.swing.JTabbedPane();
        jPanelDefault = new javax.swing.JPanel();
        jLabelDate = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jButtonSerch = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonGoToEnd = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonGoToFirst = new javax.swing.JButton();
        jButtonDelate = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jPanelAD = new javax.swing.JPanel();
        jButtonChoise = new javax.swing.JButton();
        jTextFieldDate = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jTextFieldName = new javax.swing.JTextField();
        jLabelDate1 = new javax.swing.JLabel();
        jLabelName1 = new javax.swing.JLabel();
        jLabelImage1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();

        jLabel2.setText("I");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyImageDiary");
        setResizable(false);
        setSize(new java.awt.Dimension(478, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedInteract.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jPanelDefault.setMinimumSize(new java.awt.Dimension(100, 540));
        jPanelDefault.setPreferredSize(new java.awt.Dimension(498, 540));
        jPanelDefault.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDate.setText("FECHA");
        jPanelDefault.add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 14, 60, 25));

        jTextField1.setEditable(false);
        jPanelDefault.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 15, 166, -1));

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanelDefault.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 47, 166, -1));

        jLabelName.setText("NOMBRE");
        jPanelDefault.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 46, 60, 25));

        jButtonSerch.setText("Buscar");
        jButtonSerch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSerchActionPerformed(evt);
            }
        });
        jPanelDefault.add(jButtonSerch, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 14, -1, -1));

        jButtonNext.setText(">");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        jPanelDefault.add(jButtonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 196, -1, -1));

        jButtonGoToEnd.setText("Ir final");
        jButtonGoToEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoToEndActionPerformed(evt);
            }
        });
        jPanelDefault.add(jButtonGoToEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 225, -1, -1));

        jLabelImage.setBackground(new java.awt.Color(0, 0, 0));
        jLabelImage.setText("IMAGE");
        jPanelDefault.add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 96, 290, 250));

        jButtonBack.setText("<");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanelDefault.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 196, -1, -1));

        jButtonGoToFirst.setText("Ir inicio");
        jButtonGoToFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoToFirstActionPerformed(evt);
            }
        });
        jPanelDefault.add(jButtonGoToFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 225, -1, -1));

        jButtonDelate.setText("Borrar");
        jButtonDelate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelateActionPerformed(evt);
            }
        });
        jPanelDefault.add(jButtonDelate, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 476, -1, -1));

        jButtonNew.setText("Agregar");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });
        jPanelDefault.add(jButtonNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 476, -1, -1));

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescription);

        jPanelDefault.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 359, 298, -1));

        jTabbedInteract.addTab("Diario", jPanelDefault);

        jPanelAD.setPreferredSize(new java.awt.Dimension(498, 540));
        jPanelAD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonChoise.setText("Seleccionar imagen");
        jButtonChoise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChoiseActionPerformed(evt);
            }
        });
        jPanelAD.add(jButtonChoise, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 453, -1, -1));

        jTextFieldDate.setText("DD/MM/YY");
        jTextFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateActionPerformed(evt);
            }
        });
        jPanelAD.add(jTextFieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 103, 280, -1));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanelAD.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 453, -1, -1));
        jPanelAD.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 51, 280, -1));

        jLabelDate1.setText("Fecha de la imagen:");
        jPanelAD.add(jLabelDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 80, -1, -1));

        jLabelName1.setText("Nombre de imagen:");
        jPanelAD.add(jLabelName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 28, -1, -1));

        jLabelImage1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelImage1.setText("IMAGE");
        jPanelAD.add(jLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 270, 240));

        jLabel1.setText("ID:");
        jPanelAD.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 132, 37, -1));

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        jPanelAD.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 155, 280, -1));

        jTabbedInteract.addTab("Ad", jPanelAD);

        getContentPane().add(jTabbedInteract, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSerchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSerchActionPerformed
        Serch search = new Serch();
        search.configurarOperacionDeCierre();
        search.setVisible(true);
    }//GEN-LAST:event_jButtonSerchActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:

  
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButtonChoiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChoiseActionPerformed
        metodo.captarImagen();
        metodo.mostrarImagen(jLabelImage1);
        metodo.mostrarImagen(jLabelImage);
        
        
    }//GEN-LAST:event_jButtonChoiseActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        int id = Integer.parseInt(jTextFieldID.getText());
        String fecha = jTextFieldDate.getText();
        String nombre = jTextFieldName.getText();

        // Insertar el nuevo nodo en la lista enlazada
        metodo.Insertar(id, fecha, nombre);

        String cadena = "Nombre: " + jTextFieldName.getText()
                + "\nFecha: " + jTextFieldDate.getText()
                + "\nID: " + jTextFieldID.getText();
        
        jTextAreaDescription.setText(cadena);
        
        borrarDatos();

    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonGoToFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoToFirstActionPerformed
        irPrincipio();
        metodo.mostrarImagen(jLabelImage);
        
    }//GEN-LAST:event_jButtonGoToFirstActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        if (aux != null && aux.getSiguiente() != null) {
            aux = aux.getSiguiente();
            // Mostrar la imagen del nodo actual
            metodo.mostrarImagen(jLabelImage, aux.getFoto());
        } else {
            JOptionPane.showMessageDialog(null, "No quedan más elementos por la derecha");
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        if (aux != null && aux.getAnterior() != null) {
            aux = aux.getAnterior();
            // Mostrar la imagen del nodo actual
            metodo.mostrarImagen(jLabelImage, aux.getFoto());
        } else {
            JOptionPane.showMessageDialog(null, "No quedan más elementos por la izquierda");
        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonDelateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelateActionPerformed
        int id = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la ID:"));
        metodo.eliminarDato(id);
        jLabelImage.setIcon(null);
        jLabelImage1.setIcon(null);
        jTextAreaDescription.setText(null);
        borrarDatos();
    }//GEN-LAST:event_jButtonDelateActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonGoToEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoToEndActionPerformed
        irFinal();
        metodo.mostrarImagen(jLabelImage);
    }//GEN-LAST:event_jButtonGoToEndActionPerformed

    private void jTextFieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.out.println(":c");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simplificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simplificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simplificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simplificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simplificado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonChoise;
    private javax.swing.JButton jButtonDelate;
    private javax.swing.JButton jButtonGoToEnd;
    private javax.swing.JButton jButtonGoToFirst;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonSerch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDate1;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelImage1;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelName1;
    private javax.swing.JPanel jPanelAD;
    private javax.swing.JPanel jPanelDefault;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedInteract;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
